### ISSUE TITLE
"买东西“页面无数据

### ISSUE THREAD

**Issue by chenxiqiyuan** [iinine/pddmini-coupons#5]
env.js中的微信云函数配置、app.js中的env、functions\pquery\pdd\utils.js均已更改，拼多多测试工具里面测试pdd.ddk.goods.recommend.get这个API也可以获取到数据，但打开小程序"买东西“页面白屏无数据，请问该如何解决。
谢谢!

**Comment by zhuxiaole** [comment]
你好，请问怎么解决的？？

**Comment by iinine** [comment]
咱们查看下配置的环境是否正确

zhuxiaole <notifications@github.com> 於 2021年3月4日 週四 下午5:54寫道：
