### ISSUE TITLE
想请问下拼多多的点击领卷提示正在处理，就没有反应了，pdd.ddk.member.authority.query 返回值正常

### ISSUE THREAD

**Issue by w-jx** [iinine/pddmini-coupons#6]

**Comment by Katherinaxxx** [comment]
请问怎么解决的

**Comment by w-jx** [comment]
在拼多多哪个api测试，正确输入参数，右侧返回结果的链接点一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月1日(星期四) 中午12:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [iinine/pddmini-coupons] 想请问下拼多多的点击领卷提示正在处理，就没有反应了，pdd.ddk.member.authority.query 返回值正常 (#6)





 
请问怎么解决的
